export const DATA_RECENTES = [
  {
    id: "1",
    type: "playlist",
    title: "Músicas Curtidas",
    imageUrl: require("../assets/images/liked.jpg"),
  },
  {
    id: "2",
    type: "artist",
    title: "Queens Of The Stone Age",
    description: "Álbum · Villians",
    imageUrl: require("../assets/images/qotsa.jpg"),
  },
  {
    id: "3",
    type: "playlist",
    title: "Cage the Elephant",
    imageUrl: require("../assets/images/cage_the_elephant.jpg"),
  },
  {
    id: "4",
    type: "playlist",
    title: "Portugal. The Man",
    imageUrl: require("../assets/images/portugal_the_man.jpg"),
  },
  {
    id: "5",
    type: "playlist",
    title: "Weezer",
    imageUrl: require("../assets/images/weezer.jpg"),
  },
  {
    id: "6",
    type: "playlist",
    title: "Tame Impala",
    imageUrl: require("../assets/images/tame_impala.jpg"),
  },
];

export const DATA_ARTISTAS = [
  {
    id: "1",
    type: "artist",
    title: "Tame Impala",
    imageUrl: require("../assets/images/tame_impala.jpg"),
    bgColor: "#369bad",
  },
  {
    id: "2",
    type: "artist",
    title: "Weezer",
    imageUrl: require("../assets/images/weezer.jpg"),
    bgColor: "#1167a0",
  },
  {
    id: "3",
    type: "artist",
    title: "Portugal. The Man",
    imageUrl: require("../assets/images/portugal_the_man.jpg"),
    bgColor: "#d8b374",
  },
  {
    id: "4",
    type: "artist",
    title: "Cage the Elephant",
    imageUrl: require("../assets/images/cage_the_elephant.jpg"),
    bgColor: "#d98050",
  },
  {
    id: "5",
    type: "artist",
    title: "Queens Of The Stone Age",
    imageUrl: require("../assets/images/qotsa.jpg"),
    bgColor: "#d04b52",
  },
  {
    id: "6",
    type: "artist",
    title: "Lana Del Rey",
    imageUrl: require("../assets/images/lana_del_rey.jpg"),
    bgColor: "#8692b7",
  },
];

export const DATA_PODCAST = [
  {
    id: "1",
    type: "podcast",
    title: "Hodor Cavalo",
    author: "Hodor Cavalo",
    imageUrl: require("../assets/images/hodor_cavalo.jpg"),
    bgColor: "#1C7C54",
  },
  {
    id: "2",
    type: "podcast",
    title: "His Dark Materials (Fronteidas do Universo)",
    author: "HBO Latin America",
    imageUrl: require("../assets/images/his_dark_materials.jpg"),
    bgColor: "#4c615e",
  },
  {
    id: "3",
    type: "podcast",
    title: "Popload: Podcast",
    author: "Popload",
    imageUrl: require("../assets/images/popload.jpg"),
    bgColor: "#cec98f",
  },
  {
    id: "4",
    type: "podcast",
    title: "Podcast FalaDev",
    author: "Rocketseat",
    imageUrl: require("../assets/images/fala_dev.jpg"),
    bgColor: "#7160ae",
  },
  {
    id: "5",
    type: "podcast",
    title: "Café da manhã",
    author: "Folha de S.Paulo & Spotify",
    imageUrl: require("../assets/images/cafe_da_manha.jpg"),
    bgColor: "#c6af3c",
  },
  {
    id: "6",
    type: "podcast",
    title: "Hipsters Ponto Tech",
    author: "Alura",
    imageUrl: require("../assets/images/hipsters.png"),
    bgColor: "#fac264",
  },
];
